Person.id=120
Person.name=Lally
Person.age=34
Person.langs=English,Telugu,Hindi,Tamil

Address.addrid=90
Address.city=Hyderabad
Address.state=Telangana


Employee.eid=123
Employee.ename=Raja

Department.ename=Trainer
Department.did=102

Student.sid=120
Student.sname=raju

Course.id=45
Course.name=java